#!/bin/bash

#installer2
printf '\033c'
pacman -S --noconfirm sed
sed -i "s/^#ParallelDownloads = 5$/ParallelDownloads = 10/" /etc/pacman.conf

time_zone="$(curl -s --fail https://ipapi.co/timezone)"
echo "System detected your timezone to be '$time_zone' \n"
read -p "Is this correct? [y/n]" time_zone_answer
if [[ $time_zone_answer = y ]] ; then
	ln -sf /usr/share/zoneinfo/$time_zone /etc/localtime
else 
	echo 'Enter your timezone: '
	read fixTimezone
	ln -sf /usr/share/zoneinfo/$fixTimezone /etc/localtime
fi
hwclock --systohc
echo "en_US.UTF-8 UTF-8" >> /etc/locale.gen
locale-gen
echo "LANG=en_US.UTF-8" > /etc/locale.conf
echo "KEYMAP=us" > /etc/vconsole.conf
echo "Hostname: "
read hostname
echo $hostname > /etc/hostname
echo "127.0.0.1       localhost" >> /etc/hosts
echo "::1             localhost" >> /etc/hosts
echo "127.0.1.1       $hostname.localdomain $hostname" >> /etc/hosts

mkinitcpio -P 

# installing more package
pacman --noconfirm -S grub efibootmgr os-prober xdg-user-dirs networkmanager neofetch

# root password
echo 'Enter your root password: '
passwd

# install grub
echo 'grub target[i386-efi, x86_64-efi]: '
read grubTarget
grub-install --target=$grubTarget --efi-directory=/boot --bootloader-id=arch-grub
grub-mkconfig -o /boot/grub/grub.cfg

systemctl enable NetworkManager.service

# add normal user
echo 'Enter your username: '
read MyUsername
useradd -mG wheel $MyUsername
passwd $MyUsername
echo "%wheel ALL=(ALL) ALL" >> /etc/sudoers

read -p "Install Xorg, alsa, firefox, mpv? [y/n]" InstallOtherPkgs
if [[ $InstallOtherPkgs = y ]]; then
	echo "Installing packages"
	pacman -S --noconfirm alsa-utils alsa-firmware sof-firmware alsa-ucm-conf dunst libnotify firefox ffmpeg mpv xorg-bdftopcf xorg-docs xorg-font-util xorg-fonts-100dpi xorg-fonts-75dpi xorg-fonts-encodings xorg-iceauth xorg-mkfontscale xorg-server xorg-server-common xorg-server-devel xorg-server-xephyr xorg-server-xnest xorg-server-xvfb xorg-sessreg xorg-setxkbmap xorg-smproxy xorg-x11perf xorg-xauth xorg-xbacklight xorg-xcmsdb xorg-xcursorgen xorg-xdpyinfo xorg-xdriinfo xorg-xev xorg-xgamma xorg-xhost xorg-xinit xorg-xinput xorg-xkbcomp xorg-xkbevd xorg-xkbutils xorg-xkill xorg-xlsatoms xorg-xlsclients xorg-xmodmap xorg-xpr xorg-xrandr xorg-xrdb xorg-xrefresh xorg-xsetroot xorg-xvinfo xorg-xwayland xorg-xwd xorg-xwininfo xorg-xwud 
fi

read -p "Install graphics driver?" installGraphicsDriver
if [[ $installGraphicsDriver == y ]]; then
	gpu_type=$(lspci)
	echo "Installing driver packages"
	if grep -E "NVIDIA|GeForce" <<< ${gpu_type}; then
		pacman -S --noconfirm --needed nvidia
		nvidia-xconfig
	elif lspci | grep 'VGA' | grep -E "Radeon|AMD"; then
		pacman -S --noconfirm --needed xf86-video-amdgpu
	elif grep -E "Integrated Graphics Controller" <<< ${gpu_type}; then
		pacman -S --noconfirm --needed xf86-video-intel libva-intel-driver libvdpau-va-gl vulkan-intel libva-intel-driver libva-utils
	elif grep -E "Intel Corporation" <<< ${gpu_type}; then
		pacman -S --needed --noconfirm xf86-video-intel libva-intel-driver libvdpau-va-gl vulkan-intel libva-intel-driver libva-utils
	else 
		echo "Unrecognized GPU/No GPU detected"
	fi
else
	echo "Skipping the driver installation!"
fi

echo 'Base system installation done!'
echo 'run umount -a && reboot'
exit

